version: '3.9'

networks:
  fpfssnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/16
          gateway: 10.50.0.1

services:
  database:
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" # TODO unmap in prod
    volumes:
      - fpfssdb_data:/var/lib/mysql
    networks:
      fpfssnetwork:
        ipv4_address: 10.50.0.2
    command: mysqld --max_allowed_packet=256M --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --log_bin_trust_function_creators=1
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    image: postgres:15
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4g
        reservations:
          memory: 512m
    volumes:
      - fpfss_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:${POSTGRES_PORT}"
    networks:
      fpfssnetwork:
        ipv4_address: 10.50.0.3
  validator:
    container_name: ${VALIDATOR_CONTAINER_NAME}
    restart: unless-stopped
    image: fpfss-validator:latest
    build:
      context: ./validator
      dockerfile: Dockerfile
    volumes:
      - $SUBMISSIONS_DIR_FULL_PATH:$SUBMISSIONS_DIR_FULL_PATH
    ports:
      - "8000:8000"
    networks:
      fpfssnetwork:
        ipv4_address: 10.50.0.4

volumes:
  fpfssdb_data:
  fpfss_postgres_data:
