version: '3.9'

networks:
  fpfssnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.50.0.0/16
          gateway: 10.50.0.1

services:
  database:
    container_name: fpfssdb
    restart: unless-stopped
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" # TODO unmap in prod
    volumes:
      - fpfssdb_data:/var/lib/mysql
    networks:
      fpfssnetwork:
        ipv4_address: 10.50.0.2
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --log_bin_trust_function_creators=1

volumes:
  fpfssdb_data:
